[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "london"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
monad_testnet = "https://rpc.ankr.com/monad_testnet"

[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
monad_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://testnet-explorer.monad.xyz/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
